# Generated by Django 4.1.6 on 2023-02-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('aadhar', models.CharField(max_length=12)),
                ('pan', models.CharField(max_length=10)),
                ('place_of_study', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=8)),
                ('scheme_name', models.CharField(max_length=122)),
            ],
        ),
    ]
