# Generated by Django 4.1.6 on 2023-02-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0004_rename_date_apply_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=12)),
                ('pan', models.CharField(max_length=10)),
            ],
        ),
    ]
