# Generated by Django 4.1.6 on 2023-03-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0005_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
