# Generated by Django 4.1.6 on 2023-03-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0006_apply_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=12)),
            ],
        ),
    ]
