# Generated by Django 4.1.6 on 2023-03-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0008_abrl_dob_abrl_email_abrl_gender_abrl_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hdfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=122, null=True)),
                ('dob', models.DateField(default=None, null=True)),
                ('email', models.EmailField(default=None, max_length=122, null=True)),
                ('phone', models.CharField(default=None, max_length=12, null=True)),
                ('aadhar', models.CharField(default=None, max_length=12, null=True)),
                ('pan', models.CharField(default=None, max_length=10, null=True)),
                ('place_of_study', models.CharField(default=None, max_length=122, null=True)),
                ('gender', models.CharField(default=None, max_length=8, null=True)),
                ('scheme_name', models.CharField(default=None, max_length=122, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
