# Generated by Django 4.1.6 on 2023-03-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0009_hdfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('aadhar_number', models.CharField(max_length=12)),
            ],
        ),
    ]
