# Generated by Django 4.1.6 on 2023-03-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0010_cand'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='name',
            field=models.CharField(default=None, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='cand',
            name='name',
            field=models.CharField(default=None, max_length=122, null=True),
        ),
    ]
