# Generated by Django 4.2.6 on 2023-10-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0011_dummy_name_alter_cand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=225)),
                ('scheme_closing_date', models.DateField()),
                ('defective_app_verification_date', models.DateField()),
                ('institute_verification_date', models.DateField()),
                ('dno_sno_mno_verification_date', models.DateField()),
                ('guidelines_pdf', models.FileField(upload_to='guidelines_pdfs/')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
